# Forzar versión de React Native compatible con Xcode 14
$RNVersion = '0.71.8'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# Forzar versión de iOS
platform :ios, '13.0'

# Ignorar verificación de versión de Xcode
ENV['RCT_NEW_ARCH_ENABLED'] = '0'

target 'criptoar' do
  config = use_native_modules!
  
  # Solo una línea de use_react_native!
  # use_react_native!(
  #   :path => config[:reactNativePath],
  #   :hermes_enabled => true,
  #   :version => $RNVersion
  # )

  pod 'boost', :podspec => '../node_modules/react-native/third-party-podspecs/boost.podspec'

  use_react_native!(
  :path => config[:reactNativePath],
  :hermes_enabled => false,
  :fabric_enabled => false
)

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end
